name: chat_plugin_flutter
description: A Chat Sdk flutter support for Android and Ios.
version: 1.0.0
homepage: hura.asia

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: vn.asia.chat_plugin_flutter
        pluginClass: ChatPluginFlutterPlugin
      ios:
        pluginClass: ChatPluginFlutterPlugin

